export enum StatusProjeto {
  ORCAMENTO = 'ORCAMENTO',
  APROVADO = 'APROVADO',
  EM_PRODUCAO = 'EM_PRODUCAO',
  ENTREGUE = 'ENTREGUE',
  CANCELADO = 'CANCELADO',
  PRONTO = 'PRONTO',
  VENDIDO = 'VENDIDO'
}
